export const customStyles = (isDarkMode) => ({
  control: (styles) => ({
    ...styles,
    backgroundColor: isDarkMode ? '#1e293b' : '#fff',
    color: isDarkMode ? '#fff' : '#000',
    border: '2px solid #000',
    borderRadius: '5px',
    fontSize: '0.8rem',
    lineHeight: '1.75rem',
    cursor: 'pointer',
    width: "100%",
    maxWidth: "14rem",
    minWidth: "12rem",
  }),
  menu: (styles) => ({
    ...styles,
    backgroundColor: isDarkMode ? '#1e293b' : '#fff',
    color: isDarkMode ? '#fff' : '#000',
    maxWidth: "14rem",
    borderRadius: "5px",
    border: '2px solid',
  }),
  option: (styles, { isFocused }) => ({
    ...styles,
    backgroundColor: isFocused ? (isDarkMode ? '#334155' : '#eee') : 'transparent',
    color: isDarkMode ? '#fff' : '#000',
    fontSize: "0.8rem",
    lineHeight: "1.75rem",
  }),
  placeholder: (styles) => ({
    ...styles,
    color: isDarkMode ? '#cbd5e1' : '#6b7280',
    fontSize: "0.8rem",
  }),
});
